# Generated by Django 2.2.10 on 2020-11-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tardis_portal', '0041_auto_20200819_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
