# Generated by Django 2.2.10 on 2020-12-11 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def update_user_or_group(apps, schema_editor):
    ACL = apps.get_model("tardis_portal", "ObjectACL")
    USER = apps.get_model("auth", "User")
    GROUP = apps.get_model("auth", "Group")

    for acl in ACL.objects.all():
        if acl.pluginId == 'django_user':
            try:
                acl.user = USER.objects.get(pk=acl.entityId)
            except:
                print("ERROR linking ACL: id="+str(acl.id)+', userid='+str(acl.entityId))
        if acl.pluginId == 'django_group':
            try:
                acl.group = GROUP.objects.get(pk=acl.entityId)
            except:
                print("ERROR linking ACL: id="+str(acl.id)+', groupid='+str(acl.entityId))
        acl.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tardis_portal', '0042_auto_20201117_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectacl',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectacls', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='objectacl',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectacls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(update_user_or_group
        ),
    ]
