version: "2"
services:
  base:
    build:
      context: ..
      dockerfile: docker-ci/Dockerfile-base
    image: mytardis/mytardis-base
  builder:
    build:
      context: ..
      dockerfile: docker-ci/Dockerfile-build
    volumes:
      - ../wheelhouse:/wheelhouse
      - ../tardis:/home/webapp/tardis
      - ../docs:/home/webapp/docs
    depends_on:
      - base
