# Generated by Django 2.2.19 on 2021-05-04 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tardis_portal', '0046_auto_20210215_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP Address')),
                ('endpoint', models.CharField(max_length=50, verbose_name='Globus Endpoint')),
                ('managed', models.BooleanField(default=True, verbose_name='Managed')),
                ('groups', models.ManyToManyField(blank=True, related_name='remotehosts', to='auth.Group')),
                ('projects', models.ManyToManyField(blank=True, related_name='remotehosts', to='tardis_portal.Project')),
                ('users', models.ManyToManyField(blank=True, related_name='remotehosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Transfer pending'), (2, 'Transfer submitted to Globus'), (3, 'Transfer succeeded'), (4, 'Transfer failed')], default=1)),
                ('datafiles', models.ManyToManyField(related_name='transferlogs', to='tardis_portal.DataFile')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_by', to=settings.AUTH_USER_MODEL)),
                ('remote_host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globus.RemoteHost')),
            ],
        ),
    ]
